# Development application environment

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: academy-session-control
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  source:
    repoURL: https://github.com/lijcam/headsail.git
    path: ./workspace
    targetRevision: 0.0.1
  destination:
    namespace: academy-session-control
    server: https://kubernetes.default.svc