# Development application environment

---
apiVersion: v1
kind: Namespace
metadata:
  name: academy-session-control
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: academy-session-control
  namespace: openshift-gitops
spec:
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  source:
    repoURL: https://github.com/lijcam/headsail.git
    targetRevision: HEAD
    path: headsail/session/1
  destination:
    namespace: academy-session-control
    server: https://kubernetes.default.svc