---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: challenge-1
  namespace: auxiliary-student-1
spec:
  tasks:
    - name: openshift-client
      params:
        - name: SCRIPT
          value: >-
            oc get secrets argocd-secret -n openshift-gitops -o yaml;
            export ARGOCD_PASSWORD=$(oc get secret argocd-secret -n openshift-gitops -o jsonpath='{.data.admin\.password}' | base64 -d);
            echo "string: $ARGOCD_PASSWORD"
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
