{{- range $i := until (int .Values.studentCount) }}

#
# Syncwave -2  
# 
---
apiVersion: v1
kind: Namespace
metadata:
  name:  auxiliary-student-{{ add1 $i }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: auxiliary-student-{{ add1 $i }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

{{- end }}

#
# Syncwave -1
#
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
users:
  - admin

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: headsail-secret-reader
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: headsail-secret-reader-binding
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
{{- range $i := until (int .Values.studentCount) }}
  - kind: ServiceAccount
    name: {{ $.Values.serviceAccount.name }}
    namespace: auxiliary-student-{{ add1 $i }}
{{- end }}
roleRef:
  kind: Role
  name: headsail-secret-reader
  apiGroup: rbac.authorization.k8s.io

#
# Syncwave 0
#
{{- range $i := until (int .Values.studentCount) }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: auxiliary-student-{{ add1 $i }}
  name: argocd-env-secret
type: Opaque
data:
  ARGOCD_USERNAME: {{ "admin" | b64enc }}
#  {{- range $key, $value := (lookup "v1" "Secret" "openshift-gitops" "argocd-secret") }}
#  {{- printf "key %s: value %s\n" $key $value }}
#  {{- end }}
  ARGOCD_PASSWORD: {{ index (lookup "v1" "Secret" "openshift-gitops" "argocd-secret").data "admin.password" }}
{{- end }}

