# Fixtures creates the 'fixed' components of a student workspace. 
# Including namespaces, and rolebased access controls.
#
# It uses argo sync-waves to control the deployment order.
# -2 is highest priority. 0 is default priority. 
#
# https://argo-cd.readthedocs.io/en/stable/user-guide/sync-waves/#how-do-i-configure-waves
#

{{- range $i := until (int .Values.studentCount) }}

#
# sync-wave -2  
# 
---
apiVersion: v1
kind: Namespace
metadata:
  name:  auxiliary-student-{{ add1 $i }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops

{{- end }}

#
# sync-wave -1
#
---
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: cluster-admins
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
users:
  - admin

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: headsail-secret-reader
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: headsail-secret-reader-binding
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
subjects:
{{- range $i := until (int .Values.studentCount) }}
  - kind: ServiceAccount
    name: pipeline
    namespace: auxiliary-student-{{ add1 $i }}
{{- end }}
roleRef:
  kind: Role
  name: headsail-secret-reader
  apiGroup: rbac.authorization.k8s.io

#
# sync-wave 0 - objects from this point, will deploy with the 
# main application components. See app.yaml
#