{{- range $i := until (int .Values.studentCount) }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: setup
  namespace: auxiliary-student-{{ add1 $i }}
spec:
  tasks:
    - name: seed-student-configuration
      params:
        - name: student-id
          value: "{{ add1 $i }}"
      taskRef:
        kind: ClusterTask
        name: headsail-seed
    - name: provision-student-environment
      runAfter:
        - seed-student-configuration
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: challenge-1
  namespace: auxiliary-student-{{ add1 $i }}
spec:
  tasks:
    - name: updating-resources
      params:
        - name: path
          value: content/demo-session/challenges/challenge-1
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: challenge-2
  namespace: auxiliary-student-{{ add1 $i }}
spec:
  tasks:
    - name: updating-resources
      params:
        - name: path
          value: content/demo-session/challenges/challenge-2
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision
{{- end }}