---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: setup
  namespace: auxiliary-student-1
spec:
  tasks:
    - name: seed-student-configuration
      params:
        - name: student-id
          value: "1"
      taskRef:
        kind: ClusterTask
        name: headsail-seed
    - name: provision-student-environment
      runAfter:
        - seed-student-configuration
      taskRef:
        kind: ClusterTask
        name: headsail-student-provision