---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: headsail-student-provision
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: deploy
    tekton.dev/displayName: "argocd"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task syncs student Argo CD applications and waits for it to be healthy.

  params:
    - name: student-id
      type: string
      default: "1"
    - name: application-name
      description: Name of the student application to sync
      type: string
    - name: application-path
      description: Path linking to headsail challenge
      default: content/challenges/challenge-1
      type: string
    - name: revision
      description: The revision to sync to
      default: HEAD
      type: string
    - name: flags
      default: --
      type: string
    - name: argocd-version
      default: "1.8"
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
  steps:
    - name: login
      image: registry.redhat.io/openshift-gitops-1/argocd-rhel8:$(params.argocd-version)
      script: |
        #!/usr/bin/env bash
        yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";

        argocd app delete -l headsail.student-id=$(params.student-id) || true
        argocd app create 

        argocd app wait headsail.student-id=$(params.student-id) --health --sync "$(params.flags)"